name: Playwright QE Automation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - DEV
          - QA
          - UAT
        default: DEV

      suite:
        description: "Test Suite"
        required: true
        type: choice
        options:
          - Smoke
          - Regression
        default: Regression

jobs:
  playwright-tests:
    name: Run Playwright Tests

    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Display Inputs
        run: |
          echo "Environment : ${{ github.event.inputs.environment }}"
          echo "Suite       : ${{ github.event.inputs.suite }}"

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        if: github.event.inputs.suite == 'Smoke'
        run: |
          npx playwright test --grep @smoke

      - name: Run Regression Tests
        if: github.event.inputs.suite == 'Regression'
        run: |
          npx playwright test

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
          retention-days: 30
